export const REQUEST_CUSTOMER_ITEMS = 'REQUEST_CUSTOMER_ITEMS';
export const RECEIVE_CUSTOMER_ITEMS = 'RECEIVE_CUSTOMER_ITEMS';
export const REQUEST_CATEGORY = 'REQUEST_CATEGORY';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const SET_NEW_ITEM_NAME = 'SET_NEW_ITEM_NAME';
export const SET_NEW_ITEM_VALUE = 'SET_NEW_ITEM_VALUE';
export const SET_NEW_ITEM_CATEGORY = 'SET_NEW_ITEM_CATEGORY';
export const ADD_CUSTOMER_ITEM = 'ADD_CUSTOMER_ITEM';
